import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import LeftSideBar from "./(component)/leftsidebar/page";
import TopBar from "./(component)/topbar/page";
import RightSidebar from "./(component)/rightsidebar/Rightsidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (    
<div className="w-full  md:flex justify-between ">
  <div>
    <LeftSideBar />
    <TopBar/>
    </div>

<div> 
    {children}
    </div>
    

    <div>
    {/* <BottomBar /> */}
    <RightSidebar />
    </div>
</div> 
      
        
     
  );
}
